theme: jekyll-theme-slate
title: Carolina Vargas
description: A description of your website that will be used in search engine results and the site’s RSS feed.
linkedin_username: https://www.linkedin.com/in/carolina-j-vargas/
